# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c

xcode_project: Amrap.xcodeproj 
xcode_scheme: Amrap iOS Tests
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPad Pro (9.7-inch)
