# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
script: carthage update --platform ios
script: xcodebuild  -scheme 'Amrap iOS Tests' -sdk iphonesimulator test 
